### ISSUE TITLE
Breaking changes in minor version?

### ISSUE THREAD

**Issue by alex-philippov** [alippo-com/GrowthBook-SDK-Flutter#32]
We have version 1.1.1 in our project. After update to 1.2.0 we got an error
<img width="814" alt="Снимок экрана 2023-03-14 в 08 37 25" src="https://user-images.githubusercontent.com/26027059/224992957-69ce151e-3bcd-4163-a89e-40d4d99d10ae.png">

**Comment by princebansal** [comment]
Thanks for writing to us. We will look into the issue. Meanwhile can you use the previous version to avoid any production degradations.

**Comment by chandrabezzo** [comment]
@DK070202 I think better to implement deprecated warning first before breaking changes.

**Comment by DK070202** [comment]
> @DK070202 I think it is better to implement a deprecated warning first before breaking changes.

Yes, I do agree when changes are going to be breaking changes.
