### ISSUE TITLE
Retract Version 1.2.0

### ISSUE THREAD

**Issue by chandrabezzo** [alippo-com/GrowthBook-SDK-Flutter#35]
Since you publish new architechture with version 2.0.0. Can Growthbook team retract version 1.2.0 from your [admin dashboard](https://pub.dev/packages/growthbook_sdk_flutter/admin)? So, if anyone use caret version implementation like 
```yaml
growthbook_sdk_flutter: ^1.1.2
```
Will solve the issue automatically without any declaration from `dependency_overrides` at `pubspec.yaml`. Thanks.

**Comment by chandrabezzo** [comment]
Maybe @DK070202 can help us about this? Thanks.

**Comment by DK070202** [comment]
@chandrabezzo it would be better to reopen #32. Closing these as a duplicate of #32.

**Comment by chandrabezzo** [comment]
No @DK070202 I mean you need to unpublish version 1.2.0 from pub.dev. This approach will impact to Growthbook user. So, they must refactored to version 2.0.0 without any chance to still use v1.

**Comment by princebansal** [comment]
@chandrabezzo As desired, I have retracted 1.2.0 from pub.dev. I hope this resolves the issue.

**Comment by princebansal** [comment]
@chandrabezzo You can close this issue if you think this is resolved. Else I will close it after 7 days.

**Comment by chandrabezzo** [comment]
Thanks @princebansal we can use caret version `^1.1.2`.
