### ISSUE TITLE
conflig with dio 5.0.1

### ISSUE THREAD

**Issue by tiennguyen9988** [alippo-com/GrowthBook-SDK-Flutter#47]
Because every version of growthbook_sdk_flutter depends on dio ^4.0.6 and abs depends on dio ^5.0.1, growthbook_sdk_flutter is forbidden.
So, because abs depends on growthbook_sdk_flutter any, version solving failed.

**Comment by paulononaka** [comment]
+1

**Comment by bbcbreno** [comment]
Same here!!!

**Comment by RyanHolanda** [comment]
+1

**Comment by OnlyTarg** [comment]
+1
